# Generated by Django 5.2.17 on 2026-09-26 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiln', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlendTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blendDate', models.DateField(verbose_name='拼配日')),
                ('targetGrade', models.CharField(max_length=80, verbose_name='目标品级')),
                ('plannedTotalKg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='计划总重(kg)')),
                ('closedAt', models.DateTimeField(blank=True, null=True, verbose_name='结案时刻')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blend_tickets', to=settings.AUTH_USER_MODEL, verbose_name='开单人')),
            ],
            options={
                'verbose_name': '脂液拼配单',
                'verbose_name_plural': '脂液拼配单',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BlendTicketLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countedKg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='计入千克')),
                ('resinLot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blend_lines', to='kiln.resinlot', verbose_name='来脂批')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='kiln.blendticket', verbose_name='拼配单')),
            ],
            options={
                'verbose_name': '拼配明细',
                'verbose_name_plural': '拼配明细',
                'ordering': ['id'],
            },
        ),
    ]
